apiVersion: v1
kind: Service
metadata:
  name: mvblog-webui-test
  labels:
    run: mvblog-webui-test
spec:
  type: LoadBalancer
  ports:
  - port: 80 
    protocol: TCP
  selector:
    run: mvblog-webui-test
