apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mvblog-webui-pvc 
spec:
   accessModes:
       - ReadWriteOnce
   resources:
       requests:
          storage: 1Gi
   storageClassName: robin
